"""loan amount int nullable member_chat_id

Revision ID: 0a5491add3a1
Revises: b9e4d2c7f1a3
Create Date: 2026-06-12 00:39:09.407752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a5491add3a1'
down_revision: Union[str, Sequence[str], None] = 'b9e4d2c7f1a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fund_pool', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_chat_id', sa.Integer(), nullable=True))
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('monthly_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Integer(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.alter_column('monthly_amount',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
        batch_op.drop_column('member_chat_id')

    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('fund_pool', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###
