"""fix relationship argument in role permission

Revision ID: 1e9ac1c101c5
Revises: a3f36aa44a63
Create Date: 2026-05-30 01:36:00.301220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e9ac1c101c5'
down_revision: Union[str, Sequence[str], None] = 'a3f36aa44a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
