"""fix relationship argument in role permission

Revision ID: 4b58d11dc33b
Revises: ed8eac1904e8
Create Date: 2026-05-30 01:31:10.214340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b58d11dc33b'
down_revision: Union[str, Sequence[str], None] = 'ed8eac1904e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
