"""fix relationship argument in role permission

Revision ID: 863cd9286ad9
Revises: 1e9ac1c101c5
Create Date: 2026-05-30 01:45:34.331650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '863cd9286ad9'
down_revision: Union[str, Sequence[str], None] = '1e9ac1c101c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
