"""add new unique user role table

Revision ID: 9badcadced4f
Revises: bd56267b5a3b
Create Date: 2026-05-29 19:35:29.566718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9badcadced4f'
down_revision: Union[str, Sequence[str], None] = 'bd56267b5a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_role_unique', ['user_id', 'role_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.drop_constraint('user_role_unique', type_='unique')

    # ### end Alembic commands ###
